"""
FAQItem Model - Auto-generated FAQ entries.

Generated by app/services/faq/generator.py from the tenant's real
PrestaShop CMS pages (delivery/returns/terms/... - see
PrestaShopClient.get_cms_pages()), never hand-authored and never
fabricated: each row traces back to the CMS page it was grounded in via
source_cms_id/source_title, and the generator itself refuses to produce
anything for a page whose content has no real informational substance
(e.g. PrestaShop's own Lorem Ipsum placeholder pages) rather than
inventing a plausible-sounding answer.
"""

from sqlalchemy import Column, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID

from app.infrastructure.database.base import Base, TimestampMixin, UUIDMixin


class FAQItem(Base, UUIDMixin, TimestampMixin):
    """One generated FAQ question/answer pair for a tenant."""

    __tablename__ = "faq_items"

    tenant_id = Column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=False)
    category = Column(String(100), nullable=False)

    # Traceability back to the real CMS page this was generated from -
    # never null, since every row must be grounded in a real source.
    source_cms_id = Column(Integer, nullable=False)
    source_title = Column(String(255), nullable=False)

    __table_args__ = (
        Index("idx_faq_tenant_id", "tenant_id"),
        Index("idx_faq_tenant_source", "tenant_id", "source_cms_id"),
        {"extend_existing": True},
    )

    def __repr__(self) -> str:
        return f"<FAQItem(id={self.id}, category='{self.category}', question='{self.question[:40]}')>"
