"""
API Key Security - HMAC Request Signing

Wired into TenantContextMiddleware (see app/api/middleware/tenant_context.py):
a request authenticating with a real API key (not the dev-only X-Tenant-ID
bypass) must also sign the request with the tenant's HMAC secret, or it is
rejected. This closes the "leaked static bearer key works forever" gap: a
key alone is no longer sufficient, and signatures outside a ±5 min window
are rejected as replays.

Request signing (client side, see APIClientSigner):
    signature = HMAC-SHA256(secret, timestamp + "\n" + method + "\n" + path + "\n" + body_hash)
    Headers: X-API-Key, X-Timestamp, X-Signature

The secret itself is generated by TenantRepository.activate_and_issue_api_key
/ rotate_api_key, shown to the caller exactly once, and stored server-side
encrypted at rest (app/core/security/secret_box.py) - not hashed, since
verifying a signature requires the raw secret, not just a comparison hash.
"""

import hashlib
import hmac
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional, Tuple


@dataclass
class APIKeyConfig:
    """Configuration de sécurité des API keys"""

    # HMAC
    signature_window_seconds: int = 300  # ±5 min
    required_headers: List[str] = field(
        default_factory=lambda: ["X-Timestamp", "X-Signature", "X-API-Key"]
    )


class HMACSignatureValidator:
    """
    Valide les signatures HMAC des requêtes.

    Signature = HMAC-SHA256(secret, canonical_request)

    Canonical Request:
    - timestamp (Unix)
    - method (GET, POST, etc.)
    - path (/api/v1/chat)
    - body_hash (SHA256 du body ou empty string)
    """

    def __init__(self, config: Optional[APIKeyConfig] = None):
        self._config = config or APIKeyConfig()

    def create_signature(
        self,
        secret: str,
        timestamp: int,
        method: str,
        path: str,
        body: Optional[bytes] = None,
    ) -> str:
        """
        Crée une signature HMAC pour une requête.

        À utiliser côté client pour signer les requêtes.
        """
        canonical = self._build_canonical_request(timestamp, method, path, body)

        signature = hmac.new(secret.encode(), canonical.encode(), hashlib.sha256).hexdigest()

        return signature

    def validate_signature(
        self,
        provided_signature: str,
        secret: str,
        timestamp: int,
        method: str,
        path: str,
        body: Optional[bytes] = None,
    ) -> Tuple[bool, Optional[str]]:
        """
        Valide une signature HMAC.

        Returns:
            (is_valid, error_message)
        """
        # 1. Vérifier le timestamp (anti-replay)
        now = int(datetime.utcnow().timestamp())
        time_diff = abs(now - timestamp)

        if time_diff > self._config.signature_window_seconds:
            return False, f"Timestamp expired (diff: {time_diff}s)"

        # 2. Recalculer la signature
        expected_signature = self.create_signature(secret, timestamp, method, path, body)

        # 3. Comparaison timing-safe
        if not hmac.compare_digest(provided_signature, expected_signature):
            return False, "Invalid signature"

        return True, None

    def _build_canonical_request(
        self,
        timestamp: int,
        method: str,
        path: str,
        body: Optional[bytes] = None,
    ) -> str:
        """Construit la requête canonique pour signature"""
        body_hash = ""
        if body:
            body_hash = hashlib.sha256(body).hexdigest()

        parts = [
            str(timestamp),
            method.upper(),
            path,
            body_hash,
        ]

        return "\n".join(parts)


class APIClientSigner:
    """
    Helper pour les clients API pour signer les requêtes.

    Usage (côté client):
        signer = APIClientSigner(api_key, secret)
        headers = signer.sign_request("POST", "/api/v1/chat", body)
        response = requests.post(url, headers=headers, data=body)
    """

    def __init__(self, api_key: str, secret: str):
        self._api_key = api_key
        self._secret = secret
        self._validator = HMACSignatureValidator()

    def sign_request(
        self,
        method: str,
        path: str,
        body: Optional[bytes] = None,
    ) -> Dict[str, str]:
        """
        Crée les headers de signature pour une requête.

        Returns:
            Headers dict à ajouter à la requête
        """
        timestamp = int(datetime.utcnow().timestamp())

        signature = self._validator.create_signature(
            self._secret,
            timestamp,
            method,
            path,
            body,
        )

        return {
            "X-API-Key": self._api_key,
            "X-Timestamp": str(timestamp),
            "X-Signature": signature,
        }


__all__ = [
    "APIKeyConfig",
    "HMACSignatureValidator",
    "APIClientSigner",
]
