"""add_idempotency_key_to_messages

Revision ID: 41a15dea72c1
Revises: c164818890ec
Create Date: 2026-02-13 03:50:03.179408+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a15dea72c1'
down_revision: Union[str, None] = 'c164818890ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('idempotency_key', sa.UUID(), nullable=False))
    op.create_index('idx_message_idempotency_key', 'messages', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_messages_idempotency_key'), 'messages', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_idempotency_key'), table_name='messages')
    op.drop_index('idx_message_idempotency_key', table_name='messages')
    op.drop_column('messages', 'idempotency_key')
    # ### end Alembic commands ###

