"""add_tenant_hmac_secret

Revision ID: b7d2e9f41a06
Revises: a1f4c7d92b3e
Create Date: 2026-09-19 15:00:00.000000+00:00

Per tenant HMAC secret used to sign API requests. Stored ENCRYPTED (Fernet,
see app/core/security/secret_box.py), not hashed, because verifying a
signature needs the secret in clear. Generated by
TenantRepository.activate_and_issue_api_key / rotate_api_key and checked by
TenantContextMiddleware.

Idempotent on purpose: a development database may already have the column
(it was first added by hand).
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b7d2e9f41a06'
down_revision: Union[str, None] = 'a1f4c7d92b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE tenants ADD COLUMN IF NOT EXISTS hmac_secret_encrypted TEXT")


def downgrade() -> None:
    op.execute("ALTER TABLE tenants DROP COLUMN IF EXISTS hmac_secret_encrypted")
