"""add_core_business_models

Revision ID: c164818890ec
Revises: 
Create Date: 2026-02-13 03:32:18.310657+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c164818890ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_tenant_created_at', 'tenants', ['created_at'], unique=False)
    op.create_index('idx_tenant_is_active', 'tenants', ['is_active'], unique=False)
    op.create_index('idx_tenant_slug', 'tenants', ['slug'], unique=False)
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenants_deleted_at'), 'tenants', ['deleted_at'], unique=False)
    op.create_table('analytics_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_created_at', 'analytics_events', ['created_at'], unique=False)
    op.create_index('idx_analytics_entity', 'analytics_events', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('idx_analytics_payload_gin', 'analytics_events', ['payload'], unique=False, postgresql_using='gin')
    op.create_index('idx_analytics_tenant_date', 'analytics_events', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_analytics_tenant_type', 'analytics_events', ['tenant_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_tenant_id'), 'analytics_events', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_identifier', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'ESCALATED', 'ABANDONED', name='conversation_status'), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_created_at', 'conversations', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_conversation_status', 'conversations', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_conversation_tenant_id', 'conversations', ['tenant_id'], unique=False)
    op.create_index('idx_conversation_user_identifier', 'conversations', ['tenant_id', 'user_identifier'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('ean13', sa.String(length=13), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_short', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_tax_incl', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('manufacturer_name', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('available_for_order', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_name', 'products', ['name'], unique=False)
    op.create_index('idx_product_reference', 'products', ['reference'], unique=False)
    op.create_index('idx_product_tenant_active', 'products', ['tenant_id', 'active'], unique=False)
    op.create_index('idx_product_tenant_category', 'products', ['tenant_id', 'category_id'], unique=False)
    op.create_index('idx_product_tenant_external', 'products', ['tenant_id', 'external_id'], unique=True)
    op.create_index('idx_product_tenant_price', 'products', ['tenant_id', 'price'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('rules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rule_priority', 'rules', ['tenant_id', 'priority'], unique=False)
    op.create_index('idx_rule_tenant_active', 'rules', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_rule_tenant_id', 'rules', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rules_created_at'), 'rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_rules_deleted_at'), 'rules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_rules_tenant_id'), 'rules', ['tenant_id'], unique=False)
    op.create_table('coupons',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Integer(), nullable=True),
    sa.Column('min_purchase', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', 'CANCELLED', name='coupon_status'), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('prestashop_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coupon_code', 'coupons', ['tenant_id', 'code'], unique=True)
    op.create_index('idx_coupon_created_at', 'coupons', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_coupon_expires_at', 'coupons', ['tenant_id', 'expires_at'], unique=False)
    op.create_index('idx_coupon_status', 'coupons', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_coupon_tenant_id', 'coupons', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_coupons_conversation_id'), 'coupons', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_coupons_created_at'), 'coupons', ['created_at'], unique=False)
    op.create_index(op.f('ix_coupons_rule_id'), 'coupons', ['rule_id'], unique=False)
    op.create_index(op.f('ix_coupons_tenant_id'), 'coupons', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conv_role_created', 'messages', ['conversation_id', 'role', 'created_at'], unique=False)
    op.create_index('idx_message_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_message_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_message_tenant_created', 'messages', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_message_tenant_id', 'messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_message_tenant_id', table_name='messages')
    op.drop_index('idx_message_tenant_created', table_name='messages')
    op.drop_index('idx_message_conversation_id', table_name='messages')
    op.drop_index('idx_message_conversation_created', table_name='messages')
    op.drop_index('idx_message_conv_role_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_coupons_tenant_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_rule_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_created_at'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_conversation_id'), table_name='coupons')
    op.drop_index('idx_coupon_tenant_id', table_name='coupons')
    op.drop_index('idx_coupon_status', table_name='coupons')
    op.drop_index('idx_coupon_expires_at', table_name='coupons')
    op.drop_index('idx_coupon_created_at', table_name='coupons')
    op.drop_index('idx_coupon_code', table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_rules_tenant_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_deleted_at'), table_name='rules')
    op.drop_index(op.f('ix_rules_created_at'), table_name='rules')
    op.drop_index('idx_rule_tenant_id', table_name='rules')
    op.drop_index('idx_rule_tenant_active', table_name='rules')
    op.drop_index('idx_rule_priority', table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index('idx_product_tenant_price', table_name='products')
    op.drop_index('idx_product_tenant_external', table_name='products')
    op.drop_index('idx_product_tenant_category', table_name='products')
    op.drop_index('idx_product_tenant_active', table_name='products')
    op.drop_index('idx_product_reference', table_name='products')
    op.drop_index('idx_product_name', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index('idx_conversation_user_identifier', table_name='conversations')
    op.drop_index('idx_conversation_tenant_id', table_name='conversations')
    op.drop_index('idx_conversation_status', table_name='conversations')
    op.drop_index('idx_conversation_created_at', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_analytics_events_tenant_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    op.drop_index('idx_analytics_tenant_type', table_name='analytics_events')
    op.drop_index('idx_analytics_tenant_date', table_name='analytics_events')
    op.drop_index('idx_analytics_payload_gin', table_name='analytics_events', postgresql_using='gin')
    op.drop_index('idx_analytics_entity', table_name='analytics_events')
    op.drop_index('idx_analytics_created_at', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_tenants_deleted_at'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_index('idx_tenant_slug', table_name='tenants')
    op.drop_index('idx_tenant_is_active', table_name='tenants')
    op.drop_index('idx_tenant_created_at', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###

